# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20161211_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='op',
            field=models.CharField(default='This topic was created without an original post', max_length=10000),
        ),
    ]
