# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_topic_op'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
