# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20161211_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
