# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_profile_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='op',
            new_name='first',
        ),
    ]
