# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 03:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_auto_20161212_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('filename', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256, null=True)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('assoc_project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='associated_project', to='base.Project')),
                ('uploaded_by', models.ForeignKey(default='system', on_delete=django.db.models.deletion.CASCADE, related_name='file_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
